#!/usr/bin/env python3
# Copyright (c) Sergey Kovalevich <inndie@gmail.com>
# SPDX-License-Identifier: MIT
#
# Generate code/unicode_width_table.h: ranges of codepoints taking two terminal cells.
# Source of truth is the `wcwidth` package (pip install wcwidth), which follows the latest
# Unicode East Asian Width and emoji presentation data.
#
#   python3 tools/gen_width_table.py > code/unicode_width_table.h

import sys

import wcwidth

ranges = []
start = None
for cp in range(0x110000):
    wide = not (0xD800 <= cp <= 0xDFFF) and wcwidth.wcwidth(chr(cp)) == 2
    if wide and start is None:
        start = cp
    elif not wide and start is not None:
        ranges.append((start, cp - 1))
        start = None
if start is not None:
    ranges.append((start, 0x10FFFF))

version = sorted(wcwidth.table_wide.WIDE_EASTASIAN, key=lambda v: tuple(map(int, v.split("."))))[-1]
out = sys.stdout
out.write("// Copyright (c) Sergey Kovalevich <inndie@gmail.com>\n")
out.write("// SPDX-License-Identifier: MIT\n\n")
out.write(f"// Generated by tools/gen_width_table.py from wcwidth {wcwidth.__version__} (Unicode {version}).\n")
out.write("// Do not edit by hand.\n\n#pragma once\n\n#include <array>\n#include <cstdint>\n\nnamespace xxx::detail {\n\n")
out.write("struct width_range {\n  std::uint32_t first;\n  std::uint32_t last;\n};\n\n")
out.write(f"// codepoints taking two cells, sorted, non-overlapping ({len(ranges)} ranges)\n")
out.write(f"inline constexpr auto wide_ranges = std::to_array<width_range>({{\n")
for a, b in ranges:
    out.write(f"    {{0x{a:05X}, 0x{b:05X}}},\n")
out.write("});\n\n} // namespace xxx::detail\n")
